const actionsType = {
  CREATE_COURSE: "CREATE_COURSE",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
  LOAD_AUTHORS_SUCCESS: "LOAD_AUTHORS_SUCCESS",
  CREATE_COURSES_SUCCESS: "CREATE_COURSES_SUCCESS",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
};

export default actionsType;
